#!/bin/bash

#Performs git pull in the background, only printing a quiet error message if it fails

args="$@"

function doPull() {
	output=$(git pull $args 2>&1)
	if [[ $? != 0 ]]; then
		if [[ "$args" != "" ]]; then
			argSpc=' '
		else
			argSpc=''
		fi
		echo ''
		echo "Error: qpull failed executing command 'git pull$argSpc$args'"
		echo "$output"
	fi
}

doPull &
