#!/bin/bash

#Performs git push in the background, only printing a quiet error message if it fails

args="$@"

function doPush() {
	output=$( git push $args 2>&1 )
	if [[ $? != 0 ]]; then
		if [[ "$args" != "" ]]; then
			argSpc=' '
		else
			argSpc=''
		fi
		echo ''
		echo "Error: qpush failed executing command 'git push$argSpc$args'"
		echo "$output"
	fi
}

doPush &
