#!/bin/bash

set -e

#Converts $1 seconds into hh:mm:ss if $1 does not contain a colon, otherwise interpret it as a timestamp and convert it to seconds

# pads a string to the specified length
# $1 - the string being padded, THIS METHOD WILL MODFIY THIS VARAIBLE
# $2 - the length to pad to
# $3 - pad with (defaults to 0)
function pad() {
	padChar=0
	if [[ "$3" != "" ]]; then
		padChar="$3"
	fi

	local -n str=$1
	while [[ "${#str}" < $2 ]]; do
		str="$padChar$str"
	done
}

if [[ "$1" == "" ]]; then
	echo "Please supply an argument"
	exit 1
fi

in="$1"

#When the input is negative, negChar is set, which will then be prefixed to the output
negChar=''
if [[ "${in:0:1}" == "-" ]]; then
	isNegative=true
	in="${in:1}"
	negChar='-'
fi

if [[ "$in" == *":"* ]]; then
	UNIT_FACTOR=(1 60 3600)	#Constants to multilpy each unit by to get seconds (sec, min, hr)

	IFS=':'
	read -ra arr <<< "$in"	#Split the timecode into terms
	unset IFS #resets IFS to default

	arr=($(reverse ${arr[@]} ))	#Reverse it so it's seconds-first

	seconds=0
	unit=0

	for i in "${arr[@]}"; do
		seconds=$(( $i * ${UNIT_FACTOR[$unit]} + seconds ))

		unit=$(( $unit + 1 ))
	done

	echo "$negChar$seconds"
else
	hours=$(( "$in" / (60*60) ))
	minutes=$(( ("$in" / 60) - $hours * 60 ))
	seconds=$(( "$in" % 60 ))

	pad hours 2
	pad minutes 2
	pad seconds 2

	echo "$negChar$hours:$minutes:$seconds"

fi

